// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ReviewCard: typeof import('./src/components/ReviewCard.vue')['default']
    ReviewEditor: typeof import('./src/components/ReviewEditor.vue')['default']
    ReviewFilter: typeof import('./src/components/ReviewFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavBar: typeof import('./src/components/TopNavBar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBanner: typeof import('vuetify/lib')['VBanner']
    VBreadcrumbs: typeof import('vuetify/lib')['VBreadcrumbs']
    VBreadcrumbsDivider: typeof import('vuetify/lib')['VBreadcrumbsDivider']
    VBreadcrumbsItem: typeof import('vuetify/lib')['VBreadcrumbsItem']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VChipGroup: typeof import('vuetify/lib')['VChipGroup']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanelContent: typeof import('vuetify/lib')['VExpansionPanelContent']
    VExpansionPanelHeader: typeof import('vuetify/lib')['VExpansionPanelHeader']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VMain: typeof import('vuetify/lib')['VMain']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VRating: typeof import('vuetify/lib')['VRating']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSkeletonLoader: typeof import('vuetify/lib')['VSkeletonLoader']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}

export {}
