FROM node:lts-alpine as builder

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install

COPY . /app

RUN yarn testbuild

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

ADD default.conf /etc/nginx/conf.d/

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist .

EXPOSE 80
